In [2]:
#tokenizer = BertTokenizer.from_pretrained('bert-large-uncased')
#%pip install tensorflow
#%pip install transformers --upgrade
%pip install jupyter ipywidgets --upgrade

#from transformers import TFBertModel
#model = TFBertModel.from_pretrained("bert-large-uncased")

  Using cached jupyter-1.0.0-py2.py3-none-any.whl (2.7 kB)
  Using cached ipywidgets-8.1.1-py3-none-any.whl.metadata (2.4 kB)
  Using cached notebook-7.0.6-py3-none-any.whl.metadata (10 kB)
  Using cached qtconsole-5.5.1-py3-none-any.whl.metadata (5.1 kB)
  Using cached jupyter_console-6.6.3-py3-none-any.whl (24 kB)
  Using cached nbconvert-7.13.1-py3-none-any.whl.metadata (7.7 kB)
  Using cached widgetsnbextension-4.0.9-py3-none-any.whl.metadata (1.6 kB)
  Using cached jupyterlab_widgets-3.0.9-py3-none-any.whl.metadata (4.1 kB)
   ---------------------------------------- 0.0/139.4 kB ? eta -:--:--
   ----------- ---------------------------- 41.0/139.4 kB ? eta -:--:--
   -------------------------------------- - 133.1/139.4 kB 2.0 MB/s eta 0:00:01
   ---------------------------------------- 139.4/139.4 kB 1.4 MB/s eta 0:00:00
   ---------------------------------------- 0.0/214.9 kB ? eta -:--:--
   ------------------------------ --------- 163.8/214.9 kB 3.3 MB/s eta 0:00:01
   --------

In [1]:
#####主要用於下載 TFBertModel ####
from transformers import AutoTokenizer, TFBertModel
import tensorflow as tf

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
model = TFBertModel.from_pretrained("bert-base-uncased")
#tokenizer = BertTokenizer.from_pretrained('bert-large-uncased')
#model = TFBertModel.from_pretrained("bert-large-uncased")

inputs = tokenizer("Hello, my dog is cute", return_tensors="tf")
outputs = model(inputs)

last_hidden_states = outputs.last_hidden_state

d:\project\.venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


NameError: name 'BertTokenizer' is not defined

In [7]:
#%pip install transformers
#from transformers import BertTokenizer, TFBertModel ###因為這樣直接下載TFBertModel錯誤 =>large無法下載
#tokenizer = BertTokenizer.from_pretrained('bert-large-uncased')
#model = TFBertModel.from_pretrained("bert-large-uncased")
text = "Replace me by any text you'd like."
encoded_input = tokenizer(text, return_tensors='tf')
output = model(encoded_input)
print(output)


TFBaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=<tf.Tensor: shape=(1, 12, 768), dtype=float32, numpy=
array([[[ 0.13862698,  0.15826827, -0.2966653 , ..., -0.27084965,
         -0.28436342,  0.45808396],
        [ 0.5363638 , -0.23269652,  0.17541932, ...,  0.55402577,
          0.49807155, -0.00240819],
        [ 0.30023763, -0.34751177,  0.12084408, ..., -0.45624888,
          0.32880172,  0.8772815 ],
        ...,
        [ 0.37985995,  0.12028895,  0.8282936 , ..., -0.86237276,
         -0.59569657,  0.04711473],
        [-0.02524224, -0.7176754 , -0.6950476 , ...,  0.07574195,
         -0.66678196, -0.34007478],
        [ 0.753538  ,  0.23910883,  0.07174391, ...,  0.24671514,
         -0.64580643, -0.3212979 ]]], dtype=float32)>, pooler_output=<tf.Tensor: shape=(1, 768), dtype=float32, numpy=
array([[-0.93767864, -0.5042593 , -0.979893  ,  0.90304416,  0.93293273,
        -0.24377528,  0.8925755 ,  0.22880599, -0.9531208 , -0.99999535,
        -0.8862304 ,  0.990